- hosts: basicinside.de
  sudo: yes
  vars:
   - docroot: /var/www/
  tasks:
   - name: Install Apache2
     apt: pkg=apache2 state=installed update_cache=true
     register: apache2_installed

   - name: Create Web Root
     when: apache2_installed|success
     file: dest="{{ docroot }}" mode=775 state=directory owner=www-data group=www-data
     register: webroot_installed

   - name: Sync Web Root
     when: webroot_installed|success
     sudo: no
     synchronize: src="./jekyll/_site/" dest="{{ docroot}}" rsync_path="sudo rsync"
