# Welcome to Jekyll!
#
# This config file is meant for settings that affect  whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Kuck - @basicinside
email: robin@basicinside.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of  site, e.g. /blog
url: "http://basicinside.de" # the base hostname & protocol for  site
twitter_username: basicinside
github_username:  basicinside
linkedin_username: robin-kuck-51545b100
facebook_username: robin.basic
xing_username: Robin_Kuck


# Build settings
markdown: redcarpet
highlighter: pygments
